version: '3.8'
services:
  react-builder:
    container_name: react-component-builder
    build: .
    ports:
      - "5000:3000"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G